/**
 * Weapon data shape (v2):
 *   weapon.version === 2
 *   weapon.<melee|ranged|thrown> = { features, projectile, usage, attacks, defaultAttackId, autoGenerateDefault }
 *   weapon.ammo = { projectile, resource }   // matters when itemTags.isAmmo
 *
 * Each channel exposes its own field set:
 *   - features: properties of the weapon piece itself
 *   - projectile: properties of what is delivered to the target (replaceable by ammo for ranged)
 *   - usage: action economy / handling requirements
 */
import { normalizeNestedStorage } from '../helpers/item-nested-storage.mjs';
import { migratePersistedContainerContents, releaseDirectContainerChildrenToRoot } from '../helpers/item-container.mjs';

const SH_WEAPON_VERSION = 2;

const _shNum = (v, def = 0) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : def;
};
const _shInt = (v, def = 0, min = -Infinity) => {
  const raw = Number(v);
  if (!Number.isFinite(raw)) return def;
  return Math.max(min, Math.floor(raw));
};
const _shStr = (v, def = '') => String(v ?? def).trim();
const _shTags = (v) => {
  if (!Array.isArray(v)) return [];
  return v.map((t) => String(t ?? '').trim()).filter(Boolean);
};

/* ---------- Per-channel field defaults ---------- */

function _shDefaultMeleeFeatures() {
  return { ergonomics: 0, reach: 1, twoHanded: false, parryBonus: 0, swingSpeedTier: '' };
}
function _shPositiveHardness(v) {
  const n = Number(v);
  return Number.isFinite(n) && n > 1e-9 ? n : 1;
}

function _shDefaultMeleeProjectile() {
  return {
    damage: 0,
    damageType: '',
    armorPen: 1,
    armorDamageFactor: 1,
    hardness: 1,
    projectilesPerUse: 1,
    payloadId: '',
    combatPartTag: '',
  };
}
function _shDefaultMeleeUsage() {
  return { apCost: 0, requiresHolding: false, requiresReadyState: false };
}

function _shDefaultRangedFeatures() {
  return {
    ergonomics: 0,
    accuracy: 0,
    recoil: 0,
    chamberEnabled: false,
    effectiveRange: 0,
    maxRange: 0,
    twoHanded: false,
  };
}
function _shDefaultRangedProjectile() {
  return {
    damage: 0,
    damageType: '',
    armorPen: 1,
    armorDamageFactor: 1,
    hardness: 1,
    projectilesPerUse: 1,
    payloadId: '',
  };
}
function _shDefaultRangedUsage() {
  return {
    apCost: 0,
    reloadApCost: 0,
    reloadRule: 'full',
    feedSource: 'attachedContainer',
    ammoUseMode: 'attachedContainer',
    takeFromActorInventory: false,
    attachedContainerId: '',
    feedFilterTags: [],
    consumePerUse: 1,
    chamberCurrentId: '',
    canKeepChamberOnReload: true,
    requiresHolding: false,
    requiresReadyState: false,
    requiresAimState: false,
  };
}

function _shDefaultThrownFeatures() {
  return { ergonomics: 0, accuracy: 0, throwRange: 0, aerodynamics: 0, twoHanded: false };
}
function _shDefaultThrownProjectile() {
  return {
    damage: 0,
    damageType: '',
    armorPen: 1,
    armorDamageFactor: 1,
    hardness: 1,
    projectilesPerUse: 1,
    payloadId: '',
    aoeRadius: 0,
  };
}
function _shDefaultThrownUsage() {
  return {
    apCost: 0,
    prepareApCost: 0,
    consumeOnUse: false,
    retrievable: false,
    requiresHolding: false,
    requiresReadyState: false,
  };
}

function _shDefaultAmmoResource() {
  return { resourceType: 'cartridge', caliberTag: '', compatibilityTags: [], stackMax: 0 };
}

/* ---------- Per-channel normalizers ---------- */

function _shNormMeleeFeatures(o) {
  const d = _shDefaultMeleeFeatures();
  if (!o || typeof o !== 'object') return d;
  return {
    ergonomics: _shNum(o.ergonomics, d.ergonomics),
    reach: _shNum(o.reach, d.reach),
    twoHanded: !!o.twoHanded,
    parryBonus: _shNum(o.parryBonus, d.parryBonus),
    swingSpeedTier: _shStr(o.swingSpeedTier, d.swingSpeedTier),
  };
}
function _shNormMeleeProjectile(o) {
  const d = _shDefaultMeleeProjectile();
  if (!o || typeof o !== 'object') return d;
  return {
    damage: _shNum(o.damage, d.damage),
    damageType: _shStr(o.damageType, d.damageType),
    armorPen: _shNum(o.armorPen, d.armorPen),
    armorDamageFactor: _shNum(o.armorDamageFactor, d.armorDamageFactor),
    hardness: _shPositiveHardness(o.hardness ?? d.hardness),
    projectilesPerUse: _shInt(o.projectilesPerUse, d.projectilesPerUse, 1),
    payloadId: _shStr(o.payloadId, d.payloadId),
    combatPartTag: _shStr(o.combatPartTag, d.combatPartTag),
    applications: _shNormProjectileApplications(o.applications),
    builderId: _shStr(o.builderId, ''),
  };
}
function _shNormMeleeUsage(o) {
  const d = _shDefaultMeleeUsage();
  if (!o || typeof o !== 'object') return d;
  return {
    apCost: _shInt(o.apCost, d.apCost, 0),
    requiresHolding: !!o.requiresHolding,
    requiresReadyState: !!o.requiresReadyState,
  };
}

function _shNormRangedFeatures(o) {
  const d = _shDefaultRangedFeatures();
  if (!o || typeof o !== 'object') return d;
  return {
    ergonomics: _shNum(o.ergonomics, d.ergonomics),
    accuracy: _shNum(o.accuracy, d.accuracy),
    recoil: _shNum(o.recoil, d.recoil),
    chamberEnabled: !!o.chamberEnabled,
    effectiveRange: _shNum(o.effectiveRange, d.effectiveRange),
    maxRange: _shNum(o.maxRange, d.maxRange),
    twoHanded: !!o.twoHanded,
  };
}
function _shNormRangedProjectile(o) {
  const d = _shDefaultRangedProjectile();
  if (!o || typeof o !== 'object') return d;
  return {
    damage: _shNum(o.damage, d.damage),
    damageType: _shStr(o.damageType, d.damageType),
    armorPen: _shNum(o.armorPen, d.armorPen),
    armorDamageFactor: _shNum(o.armorDamageFactor, d.armorDamageFactor),
    hardness: _shPositiveHardness(o.hardness ?? d.hardness),
    projectilesPerUse: _shInt(o.projectilesPerUse, d.projectilesPerUse, 1),
    payloadId: _shStr(o.payloadId, d.payloadId),
    applications: _shNormProjectileApplications(o.applications),
    builderId: _shStr(o.builderId, ''),
  };
}
function _shNormRangedUsage(o) {
  const d = _shDefaultRangedUsage();
  if (!o || typeof o !== 'object') return d;
  return {
    apCost: _shInt(o.apCost, d.apCost, 0),
    reloadApCost: _shInt(o.reloadApCost, d.reloadApCost, 0),
    reloadRule: _shStr(o.reloadRule, d.reloadRule) || d.reloadRule,
    feedSource: _shStr(o.feedSource, d.feedSource) || d.feedSource,
    ammoUseMode: _shStr(o.ammoUseMode ?? o.feedSource, d.ammoUseMode) || d.ammoUseMode,
    takeFromActorInventory: !!o.takeFromActorInventory,
    attachedContainerId: _shStr(o.attachedContainerId, d.attachedContainerId),
    feedFilterTags: _shTags(o.feedFilterTags),
    consumePerUse: Math.max(0, _shNum(o.consumePerUse, d.consumePerUse)),
    chamberCurrentId: _shStr(o.chamberCurrentId, d.chamberCurrentId),
    canKeepChamberOnReload: o.canKeepChamberOnReload !== false,
    requiresHolding: !!o.requiresHolding,
    requiresReadyState: !!o.requiresReadyState,
    requiresAimState: !!o.requiresAimState,
  };
}

function _shNormThrownFeatures(o) {
  const d = _shDefaultThrownFeatures();
  if (!o || typeof o !== 'object') return d;
  return {
    ergonomics: _shNum(o.ergonomics, d.ergonomics),
    accuracy: _shNum(o.accuracy, d.accuracy),
    throwRange: _shNum(o.throwRange, d.throwRange),
    aerodynamics: _shNum(o.aerodynamics, d.aerodynamics),
    twoHanded: !!o.twoHanded,
  };
}
function _shNormThrownProjectile(o) {
  const d = _shDefaultThrownProjectile();
  if (!o || typeof o !== 'object') return d;
  return {
    damage: _shNum(o.damage, d.damage),
    damageType: _shStr(o.damageType, d.damageType),
    armorPen: _shNum(o.armorPen, d.armorPen),
    armorDamageFactor: _shNum(o.armorDamageFactor, d.armorDamageFactor),
    hardness: _shPositiveHardness(o.hardness ?? d.hardness),
    projectilesPerUse: _shInt(o.projectilesPerUse, d.projectilesPerUse, 1),
    payloadId: _shStr(o.payloadId, d.payloadId),
    aoeRadius: Math.max(0, _shNum(o.aoeRadius, d.aoeRadius)),
    applications: _shNormProjectileApplications(o.applications),
    builderId: _shStr(o.builderId, ''),
  };
}

/**
 * Normalize a projectile.applications value into the canonical phased shape
 *   `[{ mode: 'sequential'|'parallel', items: [{type,damage,armorPen?,armorDamageFactor?,hardness?}, ...] }, ...]`.
 *
 * Accepts:
 *   - empty/missing → `[]` (legacy single-damage projectiles fall back to
 *     `damage`/`damageType` at runtime via `damage-resolver.normalizeApplications`).
 *   - flat array of items → wrapped in a single sequential phase.
 *   - already phased array → re-emitted with sanitised entries.
 *
 * Items with non-positive damage or unknown types are dropped silently.
 *
 * @param {unknown} raw
 * @returns {Array<{mode: string, items: Array<{type:string,damage:number,armorPen:number,armorDamageFactor:number,hardness:number}>}>}
 */
function _shNormProjectileApplications(raw) {
  if (raw == null || raw === '') return [];
  const sanitiseItem = (item) => {
    if (!item || typeof item !== 'object') return null;
    const type = String(item.type ?? '').trim();
    if (!type) return null;
    const damage = Number(item.damage ?? 0);
    if (!Number.isFinite(damage) || damage <= 0) return null;
    const armorPen = Number(item.armorPen ?? 0);
    const armorDamageFactor = Number(item.armorDamageFactor ?? 1);
    return {
      type,
      damage,
      armorPen: Number.isFinite(armorPen) && armorPen > 0 ? armorPen : 0,
      armorDamageFactor: Number.isFinite(armorDamageFactor) && armorDamageFactor > 0 ? armorDamageFactor : 1,
      hardness: _shPositiveHardness(item.hardness ?? 1),
    };
  };
  const sanitisePhase = (phase) => {
    if (!phase || typeof phase !== 'object' || !Array.isArray(phase.items)) return null;
    const mode = phase.mode === 'parallel' ? 'parallel' : 'sequential';
    const items = phase.items.map(sanitiseItem).filter(Boolean);
    if (!items.length) return null;
    return { mode, items };
  };
  if (!Array.isArray(raw)) return [];
  const looksPhased = raw.length && raw.every((entry) => entry && typeof entry === 'object' && Array.isArray(entry.items));
  if (looksPhased) return raw.map(sanitisePhase).filter(Boolean);
  const items = raw.map(sanitiseItem).filter(Boolean);
  return items.length ? [{ mode: 'sequential', items }] : [];
}

/**
 * Compose a phased applications package from a projectile config. If the
 * projectile defines an `applications` array (post-migration), use it
 * verbatim. Otherwise, build a one-item sequential package from the legacy
 * `damage`/`damageType`/`armorPen`/`armorDamageFactor`/`hardness` fields.
 *
 * Returns `[]` when the projectile carries no usable damage spec.
 *
 * @param {object} projectile
 * @returns {Array<{mode:string, items:Array<object>}>}
 */
export function buildProjectileApplications(projectile) {
  if (!projectile || typeof projectile !== 'object') return [];
  const explicit = _shNormProjectileApplications(projectile.applications);
  if (explicit.length) return explicit;
  const type = String(projectile.damageType ?? '').trim();
  const damage = Number(projectile.damage ?? 0);
  if (!type || !Number.isFinite(damage) || damage <= 0) return [];
  const armorPen = Number(projectile.armorPen ?? 0);
  const armorDamageFactor = Number(projectile.armorDamageFactor ?? 1);
  return [{
    mode: 'sequential',
    items: [{
      type,
      damage,
      armorPen: Number.isFinite(armorPen) && armorPen > 0 ? armorPen : 0,
      armorDamageFactor: Number.isFinite(armorDamageFactor) && armorDamageFactor > 0 ? armorDamageFactor : 1,
      hardness: _shPositiveHardness(projectile.hardness ?? 1),
    }],
  }];
}

/**
 * Compose the canonical phased applications package for a projectile.
 * Order of precedence:
 *   1. If `projectile.builderId` is set and the corresponding entry exists
 *      in `CONFIG.SPACEHOLDER.applicationBuilders`, invoke it with `ctx`
 *      (`{ projectile, ...ctx }`) and use whatever it returns. The builder
 *      may return either a phased array, a flat array of items, or a
 *      legacy `{type, damage}` pair — anything `_shNormProjectileApplications`
 *      can normalize.
 *   2. Otherwise fall back to {@link buildProjectileApplications}, which
 *      uses `projectile.applications` if present and the legacy
 *      single-shot fields otherwise.
 *
 * Builder failures are logged and silently fall through to the static path.
 *
 * @param {object} projectile
 * @param {object} [ctx] - extra context forwarded to the builder
 * @returns {Array<{mode:string, items:Array<object>}>}
 */
export function composeProjectileApplications(projectile, ctx = {}) {
  if (!projectile || typeof projectile !== 'object') return [];
  const builderId = String(projectile.builderId ?? '').trim();
  if (builderId) {
    const registry = (typeof CONFIG !== 'undefined' && CONFIG?.SPACEHOLDER?.applicationBuilders) || {};
    const builder = registry[builderId];
    if (typeof builder === 'function') {
      try {
        const built = builder({ ...ctx, projectile });
        const phases = _shNormProjectileApplications(built);
        if (phases.length) return phases;
      } catch (e) {
        console.error(`SpaceHolder | Application builder "${builderId}" failed:`, e);
      }
    } else {
      console.warn(`SpaceHolder | Unknown application builder id: ${builderId}`);
    }
  }
  return buildProjectileApplications(projectile);
}
function _shNormThrownUsage(o) {
  const d = _shDefaultThrownUsage();
  if (!o || typeof o !== 'object') return d;
  return {
    apCost: _shInt(o.apCost, d.apCost, 0),
    prepareApCost: _shInt(o.prepareApCost, d.prepareApCost, 0),
    consumeOnUse: !!o.consumeOnUse,
    retrievable: !!o.retrievable,
    requiresHolding: !!o.requiresHolding,
    requiresReadyState: !!o.requiresReadyState,
  };
}

const CHANNEL_NORMALIZERS = {
  melee: { features: _shNormMeleeFeatures, projectile: _shNormMeleeProjectile, usage: _shNormMeleeUsage },
  ranged: { features: _shNormRangedFeatures, projectile: _shNormRangedProjectile, usage: _shNormRangedUsage },
  thrown: { features: _shNormThrownFeatures, projectile: _shNormThrownProjectile, usage: _shNormThrownUsage },
};

/** @returns {object} */
function _shDefaultAttackModifiers() {
  return {
    apCostAdd: 0,
    accuracyAdd: 0,
    recoilAdd: 0,
    damageAdd: 0,
    projectilesPerUseAdd: 0,
    damageMult: 1,
    armorPenAdd: 0,
    armorDamageFactorMult: 1,
    hardnessMult: 1,
  };
}

/** @returns {object} */
function _shDefaultAttackOverrides() {
  return {
    apCost: null,
    accuracy: null,
    recoil: null,
    projectilesPerUse: null,
    damage: null,
    damageType: null,
    armorPen: null,
    armorDamageFactor: null,
    hardness: null,
    payloadId: null,
    requiresReadyState: null,
    requiresAimState: null,
  };
}

/**
 * @param {object} m
 * @returns {object}
 */
function _shNormalizeAttackModifiers(m) {
  const d = _shDefaultAttackModifiers();
  if (!m || typeof m !== 'object') return { ...d };
  const dm = Number(m.damageMult);
  const adm = Number(m.armorDamageFactorMult);
  const hmm = Number(m.hardnessMult);
  return {
    apCostAdd: Number(m.apCostAdd) || 0,
    accuracyAdd: Number(m.accuracyAdd) || 0,
    recoilAdd: Number(m.recoilAdd) || 0,
    damageAdd: Number(m.damageAdd) || 0,
    projectilesPerUseAdd: Number(m.projectilesPerUseAdd) || 0,
    damageMult: Number.isFinite(dm) && dm !== 0 ? dm : 1,
    armorPenAdd: Number(m.armorPenAdd) || 0,
    armorDamageFactorMult: Number.isFinite(adm) && adm !== 0 ? adm : 1,
    hardnessMult: Number.isFinite(hmm) && hmm !== 0 ? hmm : 1,
  };
}

/**
 * @param {object} o
 * @returns {object}
 */
function _shNormalizeAttackOverrides(o) {
  const d = _shDefaultAttackOverrides();
  if (!o || typeof o !== 'object') return { ...d };
  const readNum = (v) => (v === '' || v === undefined || v === null ? null : Number(v));
  const readBool = (v) => (v === '' || v === undefined || v === null ? null : !!v);
  return {
    apCost: readNum(o.apCost),
    accuracy: readNum(o.accuracy),
    recoil: readNum(o.recoil),
    projectilesPerUse: readNum(o.projectilesPerUse),
    damage: readNum(o.damage),
    damageType: o.damageType === '' || o.damageType === undefined || o.damageType === null
      ? null
      : String(o.damageType).trim(),
    armorPen: readNum(o.armorPen),
    armorDamageFactor: readNum(o.armorDamageFactor),
    hardness: readNum(o.hardness),
    payloadId: o.payloadId === '' || o.payloadId === undefined || o.payloadId === null
      ? null
      : String(o.payloadId).trim(),
    requiresReadyState: readBool(o.requiresReadyState),
    requiresAimState: readBool(o.requiresAimState),
  };
}

/**
 * @param {object} a
 * @param {string} channel
 * @returns {object}
 */
function _shNormalizeAttackVariant(a, channel) {
  const d = {
    id: '',
    name: '',
    channel,
    isDefault: false,
    origin: 'manual',
    enabled: true,
    mode: 'single',
    description: '',
    modifiers: _shDefaultAttackModifiers(),
    overrides: _shDefaultAttackOverrides(),
  };
  if (!a || typeof a !== 'object') return d;
  return {
    id: String(a.id ?? '').trim(),
    name: String(a.name ?? '').trim(),
    channel: String(a.channel ?? channel).trim() || channel,
    isDefault: !!a.isDefault,
    origin: String(a.origin ?? 'manual').trim() || 'manual',
    enabled: a.enabled !== false,
    mode: String(a.mode ?? 'single').trim() || 'single',
    description: String(a.description ?? '').trim(),
    modifiers: _shNormalizeAttackModifiers(a.modifiers),
    overrides: _shNormalizeAttackOverrides(a.overrides),
  };
}

/**
 * @param {object} ch
 * @param {'melee'|'ranged'|'thrown'} channelKey
 * @param {object} itemTags
 * @returns {object}
 */
function _shNormalizeWeaponChannel(ch, channelKey, itemTags) {
  const norm = CHANNEL_NORMALIZERS[channelKey];
  if (!norm) {
    return {
      features: {},
      projectile: {},
      usage: {},
      attacks: [],
      defaultAttackId: null,
      autoGenerateDefault: true,
    };
  }
  if (!ch || typeof ch !== 'object') ch = {};

  const features = norm.features(ch.features);
  const projectile = norm.projectile(ch.projectile);
  const usage = norm.usage(ch.usage);

  const attacks = Array.isArray(ch.attacks)
    ? ch.attacks.map((a) => _shNormalizeAttackVariant(a, channelKey))
    : [];
  let defaultAttackId =
    ch.defaultAttackId === undefined || ch.defaultAttackId === null
      ? null
      : String(ch.defaultAttackId).trim() || null;
  const autoGenerateDefault = ch.autoGenerateDefault !== false;

  const tagKey =
    channelKey === 'melee' ? 'isMelee' : channelKey === 'ranged' ? 'isRanged' : 'isThrown';
  if (itemTags?.[tagKey] && autoGenerateDefault && attacks.length === 0) {
    let rid = '';
    try {
      rid = foundry.utils.randomID?.() ?? '';
    } catch (_) {
      rid = '';
    }
    if (!rid) rid = `atk_${Date.now().toString(36)}`;
    const def = _shNormalizeAttackVariant(
      {
        id: rid,
        name: 'Default',
        channel: channelKey,
        isDefault: true,
        origin: 'auto',
        enabled: true,
        mode: 'single',
        description: '',
        modifiers: _shDefaultAttackModifiers(),
        overrides: _shDefaultAttackOverrides(),
      },
      channelKey
    );
    attacks.push(def);
    defaultAttackId = rid;
  }

  for (const atk of attacks) {
    if (!atk.id) {
      try {
        atk.id = foundry.utils.randomID?.() ?? `atk_${Date.now().toString(36)}`;
      } catch (_) {
        atk.id = `atk_${Date.now().toString(36)}`;
      }
    }
    atk.channel = channelKey;
  }

  return { features, projectile, usage, attacks, defaultAttackId, autoGenerateDefault };
}

/**
 * Normalize ammo config (v2): { projectile, resource }.
 * `projectile` shares shape with ranged.projectile so it can replace it on equip.
 * `resource` describes what the ammo IS as a stack/resource (caliber/compat/stack).
 * @param {object} ammo
 * @returns {object}
 */
function _shNormalizeAmmoConfig(ammo) {
  const proj = ammo && typeof ammo === 'object' ? ammo.projectile : null;
  const res = ammo && typeof ammo === 'object' ? ammo.resource : null;
  return {
    projectile: _shNormRangedProjectile(proj),
    resource: _shNormalizeAmmoResource(res),
  };
}

function _shNormalizeAmmoResource(o) {
  const d = _shDefaultAmmoResource();
  if (!o || typeof o !== 'object') return d;
  return {
    resourceType: _shStr(o.resourceType, d.resourceType) || d.resourceType,
    caliberTag: _shStr(o.caliberTag, d.caliberTag),
    compatibilityTags: _shTags(o.compatibilityTags),
    stackMax: Math.max(0, _shInt(o.stackMax, d.stackMax, 0)),
  };
}

/* ---------- v1 -> v2 migration ---------- */

/**
 * Detects the legacy v1 weapon shape: per-channel `base` blob, flat ammo keys.
 * @param {object} weapon
 * @returns {boolean}
 */
function _shHasV1WeaponShape(weapon) {
  if (!weapon || typeof weapon !== 'object') return false;
  const v = Math.max(0, Math.floor(Number(weapon.version) || 0));
  if (v >= 2) return false;
  for (const k of ['melee', 'ranged', 'thrown']) {
    const ch = weapon[k];
    if (ch && typeof ch === 'object' && ch.base && typeof ch.base === 'object') return true;
  }
  const ammo = weapon.ammo;
  if (ammo && typeof ammo === 'object') {
    const v1AmmoKeys = [
      'resourceType',
      'consumePerUse',
      'chamberEnabled',
      'chamberCurrentId',
      'feedSource',
      'feedFilterTags',
      'reloadApCost',
      'reloadRule',
      'canKeepChamberOnReload',
    ];
    if (v1AmmoKeys.some((k) => Object.prototype.hasOwnProperty.call(ammo, k))) return true;
  }
  return false;
}

/**
 * Translate a single v1 channel + the (shared) v1 ammo block to a v2 channel object.
 * Pulls only the fields that have natural homes in the new groups.
 * @param {'melee'|'ranged'|'thrown'} channelKey
 * @param {object} oldCh
 * @param {object} oldAmmo
 * @returns {object}
 */
function _shMigrateChannelV1(channelKey, oldCh, oldAmmo) {
  const base = oldCh && typeof oldCh === 'object' && oldCh.base && typeof oldCh.base === 'object'
    ? oldCh.base
    : {};
  const projCommon = {
    damage: base.damage,
    damageType: base.damageType,
    armorPen: base.armorPen,
    armorDamageFactor: base.armorDamageFactor,
    hardness: base.hardness != null ? base.hardness : 1,
    projectilesPerUse: base.projectilesPerUse,
    payloadId: base.payloadId,
  };
  if (channelKey === 'melee') {
    return {
      features: _shDefaultMeleeFeatures(),
      projectile: { ...projCommon, combatPartTag: '' },
      usage: {
        apCost: base.apCost,
        requiresHolding: base.requiresHolding,
        requiresReadyState: base.requiresReadyState,
      },
    };
  }
  if (channelKey === 'ranged') {
    return {
      features: {
        ergonomics: 0,
        accuracy: base.accuracy,
        recoil: base.recoil,
        chamberEnabled: !!(oldAmmo && oldAmmo.chamberEnabled),
        effectiveRange: 0,
        maxRange: 0,
        twoHanded: false,
      },
      projectile: { ...projCommon },
      usage: {
        apCost: base.apCost,
        reloadApCost: oldAmmo?.reloadApCost,
        reloadRule: oldAmmo?.reloadRule,
        feedSource: oldAmmo?.feedSource,
        ammoUseMode: oldAmmo?.ammoUseMode ?? oldAmmo?.feedSource,
        takeFromActorInventory: oldAmmo?.takeFromActorInventory,
        attachedContainerId: oldAmmo?.attachedContainerId,
        feedFilterTags: oldAmmo?.feedFilterTags,
        consumePerUse: oldAmmo?.consumePerUse,
        chamberCurrentId: oldAmmo?.chamberCurrentId,
        canKeepChamberOnReload: oldAmmo?.canKeepChamberOnReload,
        requiresHolding: base.requiresHolding,
        requiresReadyState: base.requiresReadyState,
        requiresAimState: base.requiresAimState,
      },
    };
  }
  return {
    features: {
      ergonomics: 0,
      accuracy: base.accuracy,
      throwRange: 0,
      aerodynamics: 0,
      twoHanded: false,
    },
    projectile: { ...projCommon, aoeRadius: 0 },
    usage: {
      apCost: base.apCost,
      prepareApCost: 0,
      consumeOnUse: false,
      retrievable: false,
      requiresHolding: base.requiresHolding,
      requiresReadyState: base.requiresReadyState,
    },
  };
}

/**
 * @param {object} weapon
 * @returns {object}
 */
function _shMigrateWeaponV1ToV2(weapon) {
  const w = weapon && typeof weapon === 'object' ? weapon : {};
  const oldAmmo = w.ammo && typeof w.ammo === 'object' ? w.ammo : {};
  const next = { version: SH_WEAPON_VERSION };

  for (const k of ['melee', 'ranged', 'thrown']) {
    const oldCh = w[k] && typeof w[k] === 'object' ? w[k] : {};
    const migrated = _shMigrateChannelV1(k, oldCh, oldAmmo);
    next[k] = {
      ...migrated,
      attacks: Array.isArray(oldCh.attacks) ? oldCh.attacks : [],
      defaultAttackId: oldCh.defaultAttackId ?? null,
      autoGenerateDefault: oldCh.autoGenerateDefault !== false,
    };
  }

  const oldRangedBase =
    w.ranged && w.ranged.base && typeof w.ranged.base === 'object' ? w.ranged.base : null;
  const ammoProjectile = oldRangedBase
    ? {
        damage: oldRangedBase.damage,
        damageType: oldRangedBase.damageType,
        armorPen: oldRangedBase.armorPen,
        armorDamageFactor: oldRangedBase.armorDamageFactor,
        hardness: oldRangedBase.hardness != null ? oldRangedBase.hardness : 1,
        projectilesPerUse: oldRangedBase.projectilesPerUse,
        payloadId: oldRangedBase.payloadId,
      }
    : {};
  next.ammo = {
    projectile: ammoProjectile,
    resource: {
      resourceType: oldAmmo.resourceType,
      caliberTag: '',
      compatibilityTags: Array.isArray(oldAmmo.feedFilterTags) ? oldAmmo.feedFilterTags : [],
      stackMax: 0,
    },
  };
  return next;
}

/**
 * @param {object} weapon
 * @param {object} itemTags
 * @returns {object}
 */
function _shMigrateWeaponConfig(weapon, itemTags) {
  let w = weapon;
  if (_shHasV1WeaponShape(w)) {
    w = _shMigrateWeaponV1ToV2(w);
  }
  if (!w || typeof w !== 'object') w = { version: SH_WEAPON_VERSION };
  return {
    version: SH_WEAPON_VERSION,
    melee: _shNormalizeWeaponChannel(w.melee, 'melee', itemTags),
    ranged: _shNormalizeWeaponChannel(w.ranged, 'ranged', itemTags),
    thrown: _shNormalizeWeaponChannel(w.thrown, 'thrown', itemTags),
    ammo: _shNormalizeAmmoConfig(w.ammo),
  };
}

/**
 * Normalize `system.weapon` for items (sheet display + persistence).
 * @param {object} weapon
 * @param {object} itemTags
 * @returns {object}
 */
export function migrateItemWeaponData(weapon, itemTags) {
  return _shMigrateWeaponConfig(weapon, itemTags);
}

/**
 * Extend the basic Item with some very simple modifications.
 * @extends {Item}
 */
export class SpaceHolderItem extends Item {
  /**
   * v14 compatibility: short-circuit no-op updates that carry no actual changes
   * (only `_id` or completely empty). Foundry's `#onSubmitDocumentForm` can invoke
   * `_processSubmitData` with `{}` after a failed validate, and the resulting
   * `cleanData({_id})` then throws "must be constructed with a DataModel or Object".
   * The `type`/`name` injection is handled in `updateSource` (the chokepoint for
   * all update code paths).
   * @inheritDoc
   */
  async update(data, operation) {
    if (data && typeof data === 'object' && !Array.isArray(data)) {
      const meaningfulKeys = Object.keys(data).filter((k) => k !== '_id');
      if (meaningfulKeys.length === 0) return this;
    }
    return super.update(data, operation);
  }

  /**
   * v14 compatibility: Foundry's update pipeline (preUpdateDocumentArray,
   * #handleUpdateDocuments, and validate via _prepareSubmitData) expands partial
   * change objects via `cleanData` with `addTypes:true`, which adds schema keys
   * (`type`, `name`) but leaves them as `undefined` because static `cleanData`
   * doesn't know `_source`. Foundry's `_updateDiff` then either sees
   * `_source.type !== changes.type (undefined)` and throws "ForcedReplacement", or
   * validates `name: undefined` and throws a schema error. Inject the persisted
   * values for any required-without-default field that ended up undefined.
   * @inheritDoc
   */
  updateSource(changes, options) {
    if (changes && typeof changes === 'object' && !Array.isArray(changes)) {
      const src = this._source ?? {};
      if ((!('type' in changes) || changes.type === undefined || changes.type === null) && src.type !== undefined) {
        changes.type = src.type;
      }
      if ((!('name' in changes) || changes.name === undefined || changes.name === null) && src.name !== undefined) {
        changes.name = src.name;
      }
    }
    return super.updateSource(changes, options);
  }

  /**
   * When a container host Item is removed, direct children must not keep a stale
   * `containerHostId` or they disappear from root inventory lists.
   * @inheritDoc
   */
  async delete(options = {}) {
    if (
      this.type === 'item' &&
      this.system?.itemTags?.isContainer &&
      this.isEmbedded === true &&
      this.actor
    ) {
      try {
        await releaseDirectContainerChildrenToRoot(this.actor, this.id);
      } catch (error) {
        console.error('SpaceHolder | release container children before Item delete', error);
      }
    }
    return super.delete(options);
  }

  /**
   * Merge legacy `wearable` into `item` and backfill unified `item.system` fields.
   * @param {object} source
   * @param {object} [migrationData]
   * @returns {object}
   */
  static migrateData(source, migrationData) {
    // v14: Foundry calls migrateData on partial update payloads via DataModelSchemaField.clean.
    // We must NOT inject schema defaults here, otherwise the diff vs. _source includes
    // spurious resets (e.g. itemTags={isArmor:false,...}) that wipe user data.
    // Only do legacy shape migration on full source documents (migrationData.partial is falsy).
    if (migrationData?.partial) return super.migrateData(source, migrationData);

    if (source.type === 'wearable') source.type = 'item';

    if (source.type === 'item' && source.system && typeof source.system === 'object') {
      const s = source.system;
      if (s.equipped === undefined) s.equipped = false;
      if (s.held === undefined) s.held = false;
      if (s.equipped) s.held = false;
      if (s.anatomyId === undefined) s.anatomyId = null;
      if (!Array.isArray(s.coveredParts)) s.coveredParts = [];
      s.storage = normalizeNestedStorage(s.storage);
      if (!s.defaultActions || typeof s.defaultActions !== 'object') {
        s.defaultActions = {
          equip: { showInCombat: false, showInQuickbar: true },
          unequip: { showInCombat: false, showInQuickbar: true },
          hold: { showInCombat: false, showInQuickbar: true },
          stow: { showInCombat: false, showInQuickbar: true },
          drop: { showInCombat: false, showInQuickbar: false },
          wear: { showInCombat: false, showInQuickbar: false },
          show: { showInCombat: false, showInQuickbar: false },
        };
      } else {
        s.defaultActions.equip = s.defaultActions.equip || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.unequip = s.defaultActions.unequip || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.hold = s.defaultActions.hold || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.stow = s.defaultActions.stow || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.drop = s.defaultActions.drop || { showInCombat: false, showInQuickbar: false };
        s.defaultActions.wear = s.defaultActions.wear || { showInCombat: false, showInQuickbar: false };
        s.defaultActions.show = s.defaultActions.show || { showInCombat: false, showInQuickbar: false };
      }
      if (!s.modifiers || typeof s.modifiers !== 'object') {
        s.modifiers = { abilities: [], derived: [], params: [] };
      } else {
        s.modifiers.abilities = Array.isArray(s.modifiers.abilities) ? s.modifiers.abilities : [];
        s.modifiers.derived = Array.isArray(s.modifiers.derived) ? s.modifiers.derived : [];
        s.modifiers.params = Array.isArray(s.modifiers.params) ? s.modifiers.params : [];
      }
      if (s.formula === undefined) {
        s.formula = 'd20 + @str.mod + ceil(@lvl / 2)';
      }
      if (s.containerHostId === undefined || s.containerHostId === null) {
        s.containerHostId = '';
      } else {
        s.containerHostId = String(s.containerHostId).trim();
      }
      if (!s.container || typeof s.container !== 'object') {
        s.container = { contents: [] };
      } else {
        const c = s.container;
        c.contents = migratePersistedContainerContents(c.contents);
      }

      if (!s.itemTags || typeof s.itemTags !== 'object') {
        s.itemTags = {
          isArmor: false,
          isActions: false,
          isModifiers: false,
          isMelee: false,
          isRanged: false,
          isThrown: false,
          isAmmo: false,
          isContainer: false,
        };
      } else {
        const t = s.itemTags;
        t.isArmor = !!t.isArmor;
        t.isActions = !!t.isActions;
        t.isModifiers = !!t.isModifiers;
        t.isAmmo = !!t.isAmmo;
        t.isMelee = !!t.isMelee;
        t.isRanged = !!t.isRanged;
        t.isThrown = !!t.isThrown;
        t.isContainer = !!t.isContainer;
        const hadAnyWeaponKind = !!(t.isMelee || t.isRanged || t.isThrown);
        if (t.isWeapon && !hadAnyWeaponKind) t.isMelee = true;
        delete t.isWeapon;
      }

      s.weapon = _shMigrateWeaponConfig(s.weapon, s.itemTags);
    }

    return super.migrateData(source, migrationData);
  }

  /**
   * Augment the basic Item data model with additional dynamic data.
   */
  prepareData() {
    // As with the actor class, items are documents that can have their data
    // preparation methods overridden (such as prepareBaseData()).
    super.prepareData();
  }

  /**
   * Prepare a data object which defines the data schema used by dice roll commands against this Item
   * @override
   */
  getRollData() {
    // Starts off by populating the roll data with a shallow copy of `this.system`
    const rollData = { ...this.system };

    // Quit early if there's no parent actor
    if (!this.actor) return rollData;

    // If present, add the actor's roll data
    rollData.actor = this.actor.getRollData();

    return rollData;
  }

  /**
   * Handle clickable rolls.
   * @param {Event} event   The originating click event
   * @private
   */
  async roll() {
    const item = this;

    // Initialize chat data.
    const speaker = ChatMessage.getSpeaker({ actor: this.actor });
    const rollMode = game.settings.get('core', 'rollMode');
    const label = `[${item.type}] ${item.name}`;

    // If there's no roll data, send a chat message.
    if (!this.system.formula) {
      ChatMessage.create({
        speaker: speaker,
        rollMode: rollMode,
        flavor: label,
        content: item.system.description ?? '',
      });
    }
    // Otherwise, create a roll and send a chat message from it.
    else {
      // Retrieve roll data.
      const rollData = this.getRollData();

      // Invoke the roll and submit it to chat.
      const roll = new Roll(rollData.formula, rollData);
      // If you need to store the value first, uncomment the next line.
      // const result = await roll.evaluate();
      roll.toMessage({
        speaker: speaker,
        rollMode: rollMode,
        flavor: label,
      });
      return roll;
    }
  }
}
