/** @returns {object} */
function _shDefaultWeaponBaseStats() {
  return {
    apCost: 0,
    accuracy: 0,
    recoil: 0,
    projectilesPerUse: 1,
    damage: 0,
    damageType: '',
    armorPen: 0,
    armorDamageFactor: 1,
    requiresHolding: false,
    requiresReadyState: false,
    requiresAimState: false,
    payloadId: '',
  };
}

/** @returns {object} */
function _shDefaultAttackModifiers() {
  return {
    apCostAdd: 0,
    accuracyAdd: 0,
    recoilAdd: 0,
    damageAdd: 0,
    projectilesPerUseAdd: 0,
    damageMult: 1,
    armorPenAdd: 0,
    armorDamageFactorMult: 1,
  };
}

/** @returns {object} */
function _shDefaultAttackOverrides() {
  return {
    apCost: null,
    accuracy: null,
    recoil: null,
    projectilesPerUse: null,
    damage: null,
    damageType: null,
    armorPen: null,
    armorDamageFactor: null,
    payloadId: null,
    requiresReadyState: null,
    requiresAimState: null,
  };
}

/**
 * @param {object} base
 * @returns {object}
 */
function _shNormalizeWeaponBaseStats(base) {
  const d = _shDefaultWeaponBaseStats();
  if (!base || typeof base !== 'object') return { ...d };
  return {
    apCost: Math.max(0, Math.floor(Number(base.apCost) || 0)),
    accuracy: Number(base.accuracy) || 0,
    recoil: Number(base.recoil) || 0,
    projectilesPerUse: Math.max(1, Math.floor(Number(base.projectilesPerUse) || 1)),
    damage: Number(base.damage) || 0,
    damageType: String(base.damageType ?? '').trim(),
    armorPen: Number(base.armorPen) || 0,
    armorDamageFactor: Number(base.armorDamageFactor) || 0,
    requiresHolding: !!base.requiresHolding,
    requiresReadyState: !!base.requiresReadyState,
    requiresAimState: !!base.requiresAimState,
    payloadId: String(base.payloadId ?? '').trim(),
  };
}

/**
 * @param {object} m
 * @returns {object}
 */
function _shNormalizeAttackModifiers(m) {
  const d = _shDefaultAttackModifiers();
  if (!m || typeof m !== 'object') return { ...d };
  const dm = Number(m.damageMult);
  const adm = Number(m.armorDamageFactorMult);
  return {
    apCostAdd: Number(m.apCostAdd) || 0,
    accuracyAdd: Number(m.accuracyAdd) || 0,
    recoilAdd: Number(m.recoilAdd) || 0,
    damageAdd: Number(m.damageAdd) || 0,
    projectilesPerUseAdd: Number(m.projectilesPerUseAdd) || 0,
    damageMult: Number.isFinite(dm) && dm !== 0 ? dm : 1,
    armorPenAdd: Number(m.armorPenAdd) || 0,
    armorDamageFactorMult: Number.isFinite(adm) && adm !== 0 ? adm : 1,
  };
}

/**
 * @param {object} o
 * @returns {object}
 */
function _shNormalizeAttackOverrides(o) {
  const d = _shDefaultAttackOverrides();
  if (!o || typeof o !== 'object') return { ...d };
  const readNum = (v) => (v === '' || v === undefined || v === null ? null : Number(v));
  const readBool = (v) => (v === '' || v === undefined || v === null ? null : !!v);
  return {
    apCost: readNum(o.apCost),
    accuracy: readNum(o.accuracy),
    recoil: readNum(o.recoil),
    projectilesPerUse: readNum(o.projectilesPerUse),
    damage: readNum(o.damage),
    damageType: o.damageType === '' || o.damageType === undefined || o.damageType === null
      ? null
      : String(o.damageType).trim(),
    armorPen: readNum(o.armorPen),
    armorDamageFactor: readNum(o.armorDamageFactor),
    payloadId: o.payloadId === '' || o.payloadId === undefined || o.payloadId === null
      ? null
      : String(o.payloadId).trim(),
    requiresReadyState: readBool(o.requiresReadyState),
    requiresAimState: readBool(o.requiresAimState),
  };
}

/**
 * @param {object} a
 * @param {string} channel
 * @returns {object}
 */
function _shNormalizeAttackVariant(a, channel) {
  const d = {
    id: '',
    name: '',
    channel,
    isDefault: false,
    origin: 'manual',
    enabled: true,
    mode: 'single',
    description: '',
    modifiers: _shDefaultAttackModifiers(),
    overrides: _shDefaultAttackOverrides(),
  };
  if (!a || typeof a !== 'object') return d;
  return {
    id: String(a.id ?? '').trim(),
    name: String(a.name ?? '').trim(),
    channel: String(a.channel ?? channel).trim() || channel,
    isDefault: !!a.isDefault,
    origin: String(a.origin ?? 'manual').trim() || 'manual',
    enabled: a.enabled !== false,
    mode: String(a.mode ?? 'single').trim() || 'single',
    description: String(a.description ?? '').trim(),
    modifiers: _shNormalizeAttackModifiers(a.modifiers),
    overrides: _shNormalizeAttackOverrides(a.overrides),
  };
}

/**
 * @param {object} ch
 * @param {'melee'|'ranged'|'thrown'} channelKey
 * @param {object} itemTags
 * @returns {object}
 */
function _shNormalizeWeaponChannel(ch, channelKey, itemTags) {
  const baseDefaults = _shDefaultWeaponBaseStats();
  const empty = {
    base: { ...baseDefaults },
    attacks: [],
    defaultAttackId: null,
    autoGenerateDefault: true,
  };
  if (!ch || typeof ch !== 'object') ch = { ...empty };
  ch.base = _shNormalizeWeaponBaseStats(ch.base);
  ch.attacks = Array.isArray(ch.attacks)
    ? ch.attacks.map((a) => _shNormalizeAttackVariant(a, channelKey))
    : [];
  ch.defaultAttackId =
    ch.defaultAttackId === undefined || ch.defaultAttackId === null
      ? null
      : String(ch.defaultAttackId).trim() || null;
  ch.autoGenerateDefault = ch.autoGenerateDefault !== false;

  const tagKey =
    channelKey === 'melee' ? 'isMelee' : channelKey === 'ranged' ? 'isRanged' : 'isThrown';
  if (itemTags?.[tagKey] && ch.autoGenerateDefault && ch.attacks.length === 0) {
    let rid = '';
    try {
      rid = foundry.utils.randomID?.() ?? '';
    } catch (_) {
      rid = '';
    }
    if (!rid) rid = `atk_${Date.now().toString(36)}`;
    const def = _shNormalizeAttackVariant(
      {
        id: rid,
        name: 'Default',
        channel: channelKey,
        isDefault: true,
        origin: 'auto',
        enabled: true,
        mode: 'single',
        description: '',
        modifiers: _shDefaultAttackModifiers(),
        overrides: _shDefaultAttackOverrides(),
      },
      channelKey
    );
    ch.attacks = [def];
    ch.defaultAttackId = rid;
  }

  for (const atk of ch.attacks) {
    if (!atk.id) {
      try {
        atk.id = foundry.utils.randomID?.() ?? `atk_${Date.now().toString(36)}`;
      } catch (_) {
        atk.id = `atk_${Date.now().toString(36)}`;
      }
    }
    atk.channel = channelKey;
  }

  return ch;
}

/**
 * @param {object} ammo
 * @returns {object}
 */
function _shNormalizeAmmoConfig(ammo) {
  const d = {
    resourceType: 'cartridge',
    consumePerUse: 1,
    chamberEnabled: false,
    chamberCurrentId: '',
    feedSource: 'attachedContainer',
    feedFilterTags: [],
    reloadApCost: 0,
    reloadRule: 'full',
    canKeepChamberOnReload: true,
  };
  if (!ammo || typeof ammo !== 'object') return { ...d };
  const tags = Array.isArray(ammo.feedFilterTags)
    ? ammo.feedFilterTags.map((t) => String(t ?? '').trim()).filter(Boolean)
    : [];
  return {
    resourceType: String(ammo.resourceType ?? 'cartridge').trim() || 'cartridge',
    consumePerUse: Math.max(0, Number(ammo.consumePerUse) || 0),
    chamberEnabled: !!ammo.chamberEnabled,
    chamberCurrentId: String(ammo.chamberCurrentId ?? '').trim(),
    feedSource: String(ammo.feedSource ?? 'attachedContainer').trim() || 'attachedContainer',
    feedFilterTags: tags,
    reloadApCost: Math.max(0, Math.floor(Number(ammo.reloadApCost) || 0)),
    reloadRule: String(ammo.reloadRule ?? 'full').trim() || 'full',
    canKeepChamberOnReload: ammo.canKeepChamberOnReload !== false,
  };
}

/**
 * @param {object} weapon
 * @param {object} itemTags
 * @returns {object}
 */
function _shMigrateWeaponConfig(weapon, itemTags) {
  const w =
    weapon && typeof weapon === 'object'
      ? weapon
      : {
          version: 1,
          melee: {},
          ranged: {},
          thrown: {},
          ammo: {},
        };
  const version = Math.max(1, Math.floor(Number(w.version) || 1));
  return {
    version,
    melee: _shNormalizeWeaponChannel(w.melee, 'melee', itemTags),
    ranged: _shNormalizeWeaponChannel(w.ranged, 'ranged', itemTags),
    thrown: _shNormalizeWeaponChannel(w.thrown, 'thrown', itemTags),
    ammo: _shNormalizeAmmoConfig(w.ammo),
  };
}

/**
 * Normalize `system.weapon` for items (sheet display + persistence).
 * @param {object} weapon
 * @param {object} itemTags
 * @returns {object}
 */
export function migrateItemWeaponData(weapon, itemTags) {
  return _shMigrateWeaponConfig(weapon, itemTags);
}

/**
 * Extend the basic Item with some very simple modifications.
 * @extends {Item}
 */
export class SpaceHolderItem extends Item {
  /**
   * Merge legacy `wearable` into `item` and backfill unified `item.system` fields.
   * @param {object} source
   * @param {object} [migrationData]
   * @returns {object}
   */
  static migrateData(source, migrationData) {
    if (source.type === 'wearable') source.type = 'item';

    if (source.type === 'item' && source.system && typeof source.system === 'object') {
      const s = source.system;
      if (s.equipped === undefined) s.equipped = false;
      if (s.held === undefined) s.held = false;
      if (s.equipped) s.held = false;
      if (s.anatomyId === undefined) s.anatomyId = null;
      if (!Array.isArray(s.coveredParts)) s.coveredParts = [];
      if (!s.defaultActions || typeof s.defaultActions !== 'object') {
        s.defaultActions = {
          equip: { showInCombat: false, showInQuickbar: true },
          unequip: { showInCombat: false, showInQuickbar: true },
          hold: { showInCombat: false, showInQuickbar: true },
          stow: { showInCombat: false, showInQuickbar: true },
          drop: { showInCombat: false, showInQuickbar: false },
          wear: { showInCombat: false, showInQuickbar: false },
          show: { showInCombat: false, showInQuickbar: false },
        };
      } else {
        s.defaultActions.equip = s.defaultActions.equip || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.unequip = s.defaultActions.unequip || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.hold = s.defaultActions.hold || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.stow = s.defaultActions.stow || { showInCombat: false, showInQuickbar: true };
        s.defaultActions.drop = s.defaultActions.drop || { showInCombat: false, showInQuickbar: false };
        s.defaultActions.wear = s.defaultActions.wear || { showInCombat: false, showInQuickbar: false };
        s.defaultActions.show = s.defaultActions.show || { showInCombat: false, showInQuickbar: false };
      }
      if (!s.modifiers || typeof s.modifiers !== 'object') {
        s.modifiers = { abilities: [], derived: [], params: [] };
      } else {
        s.modifiers.abilities = Array.isArray(s.modifiers.abilities) ? s.modifiers.abilities : [];
        s.modifiers.derived = Array.isArray(s.modifiers.derived) ? s.modifiers.derived : [];
        s.modifiers.params = Array.isArray(s.modifiers.params) ? s.modifiers.params : [];
      }
      if (s.formula === undefined) {
        s.formula = 'd20 + @str.mod + ceil(@lvl / 2)';
      }
      if (!s.itemTags || typeof s.itemTags !== 'object') {
        s.itemTags = {
          isArmor: false,
          isActions: false,
          isModifiers: false,
          isMelee: false,
          isRanged: false,
          isThrown: false,
          isAmmo: false,
        };
      } else {
        const t = s.itemTags;
        t.isArmor = !!t.isArmor;
        t.isActions = !!t.isActions;
        t.isModifiers = !!t.isModifiers;
        t.isAmmo = !!t.isAmmo;
        t.isMelee = !!t.isMelee;
        t.isRanged = !!t.isRanged;
        t.isThrown = !!t.isThrown;
        const hadAnyWeaponKind = !!(t.isMelee || t.isRanged || t.isThrown);
        if (t.isWeapon && !hadAnyWeaponKind) t.isMelee = true;
        delete t.isWeapon;
      }

      s.weapon = _shMigrateWeaponConfig(s.weapon, s.itemTags);
    }

    return super.migrateData(source, migrationData);
  }

  /**
   * Augment the basic Item data model with additional dynamic data.
   */
  prepareData() {
    // As with the actor class, items are documents that can have their data
    // preparation methods overridden (such as prepareBaseData()).
    super.prepareData();
  }

  /**
   * Prepare a data object which defines the data schema used by dice roll commands against this Item
   * @override
   */
  getRollData() {
    // Starts off by populating the roll data with a shallow copy of `this.system`
    const rollData = { ...this.system };

    // Quit early if there's no parent actor
    if (!this.actor) return rollData;

    // If present, add the actor's roll data
    rollData.actor = this.actor.getRollData();

    return rollData;
  }

  /**
   * Handle clickable rolls.
   * @param {Event} event   The originating click event
   * @private
   */
  async roll() {
    const item = this;

    // Initialize chat data.
    const speaker = ChatMessage.getSpeaker({ actor: this.actor });
    const rollMode = game.settings.get('core', 'rollMode');
    const label = `[${item.type}] ${item.name}`;

    // If there's no roll data, send a chat message.
    if (!this.system.formula) {
      ChatMessage.create({
        speaker: speaker,
        rollMode: rollMode,
        flavor: label,
        content: item.system.description ?? '',
      });
    }
    // Otherwise, create a roll and send a chat message from it.
    else {
      // Retrieve roll data.
      const rollData = this.getRollData();

      // Invoke the roll and submit it to chat.
      const roll = new Roll(rollData.formula, rollData);
      // If you need to store the value first, uncomment the next line.
      // const result = await roll.evaluate();
      roll.toMessage({
        speaker: speaker,
        rollMode: rollMode,
        flavor: label,
      });
      return roll;
    }
  }
}
